import = [
        "~/.config/alacritty/terminal_app.toml"
]

[window]
title = "pramitgaha"
dynamic_title = false
startup_mode = "Maximized"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 15

[mouse]
hide_when_typing = true
